sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t victorsunki/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true victorsunki/react-test npm test

after_success:
  - docker build -t victorsunki/multi-client ./client
  - docker build -t victorsunki/multi-nginx ./nginx
  - docker build -t victorsunki/multi-server ./server
  - docker build -t victorsunki/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push victorsunki/multi-client
  - docker push victorsunki/multi-nginx
  - docker push victorsunki/multi-server
  - docker push victorsunki/multi-worker
  # The End
